language: "python"
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - python ./setup.py install
  - pip install flake8

script: 
  - flake8 . --exclude=build,deeptoolsintervals/__init__.py --ignore=E501,F403,E40
  - cd ~/ && nosetests --with-doctest deeptoolsintervals
